url: https://example.com/contact
success_selector: "div.wpforms-confirmation-container"

form_fields:
  - name: name
    type: text
    required: true
    value: Alicja Kowalska

  - name: email
    type: text
    required: true
    value: alicja@example.com

  - name: message
    type: textarea
    required: true
    value: Hello! I'm interested in your services. Please contact me back.

  - name: file-upload
    type: file
    required: false
    file: testdata/file.pdf
    file-wrong: testdata/file.txt
    exclude: true

  - name: consent
    type: checkbox
    required: true
    checkbox: true

validation:
  global_success: "Your message has been sent successfully."
  global_error: "One or more fields have an error. Please check and try again."
  field_error: "The field is required."
  field_error_file_type: "You are not allowed to upload files of this type."

email_check:
  autoresponder:
    subject_contains: "Thank you for contacting us"
    must_contain:
      - "We have received your message"
      - "Our team will get back to you shortly"
    check_form_fields:
      - name
      - message
    imap:
      server: imap.mailserver.com
      port: 993
      username: contact-replies@example.com
      password: supersecret
      use_ssl: true

  form_copy:
    subject_contains: "New contact form submission"
    must_contain:
      - "New message received"
    check_form_fields:
      - name
      - email
      - message
      - file-upload
    imap:
      server: imap.mailserver.com
      port: 993
      username: contact@example.com
      password: admin123
      use_ssl: true
